### PR TITLE
Ports Xeon's Carp update

### PR DESCRIPTION
**Pull request by PapaSejd**
## About The Pull Request

Ports xeon's carp update.
https://github.com/TheSwain/Fulpstation/pull/394/files

### CODE REVIEW

**Comment by TheFakeElon** [comment]
modularise your code silly.

**Comment by coolsurf6** [comment]
Oooh elon out here being spicy.

**Comment by PapaSejd** [comment]
> modularise your code silly.

In time, in time. Ill do it when im back on my PC

**Comment by gonenoculer5** [comment]
> modularise your code silly.
We plan on it, we just need to get shit over here f i r s t.

**Comment by TheFakeElon** [comment]
Couldn’t you just modularise it first to save yourself having to go back and change it.

**Comment by PapaSejd** [comment]
> Couldn’t you just modularise it first to save yourself having to go back and change it.

Tsk tsk, you act as if ss13 coders are in any way efficient.

**Comment by PapaSejd** [comment]
undefined var issues, a lot of this is gonna have to fixed for this to work on beecode

**Comment by PapaSejd** [comment]
this will be redone

**Pull request closed without merging**
